language: c

branches:
  only:
    - master

sudo: false
dist: trusty

before_install:
  - curl -ssL -O http://downloads.arduino.cc/arduino-1.8.5-linux64.tar.xz
  - tar xf arduino-1.8.5-linux64.tar.xz
  - sudo mv arduino-1.8.5 /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino

install:
  - ln -s $PWD /usr/local/share/arduino/libraries/PCD8544

script:
  - arduino --verify --board arduino:avr:uno $PWD/examples/HelloWorld/HelloWorld.ino
  - arduino --verify --board arduino:avr:uno $PWD/examples/Thermometer/Thermometer.ino
